version: 1.0.{build}-{branch}

install:
  - nuget restore
environment:
  COVERALLS_REPO_TOKEN:
    secure: dY3e2PttmI1QXanxytUMU0TqfHWIsuxsr
build:
  project: school.sln
  verbosity: minimal

test_script:
- ps:
  .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe" -targetargs:"/domain:single src\school.shell.tests\bin\debug\school.shell.tests.dll" -output:coverage.xml
  
    $coveralls = (Resolve-Path "src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken dY3e2PttmI1QXanxytUMU0TqfHWIsuxsr
